# .air.toml
# Configuration for Air hot reload tool
# https://github.com/cosmtrek/air

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main ./cmd/api/main.go"
  
  # Binary file yields from `cmd`.
  bin = "tmp/main"
  
  # Customize binary, you can use `APP_ENV=dev air` to set environment on start
  full_bin = "APP_ENV=dev APP_PORT=8080 ./tmp/main"
  
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "sql"]
  
  # Ignore these filename extensions or directories.
  exclude_dir = [
    "assets", 
    "tmp", 
    "vendor", 
    "node_modules",
    "bin",
    "test",
    "testdata",
    ".git",
    ".github",
    "build",
    "docker",
    "scripts",
    "docs",
    "invoices",
    "uploads"
  ]
  
  # Watch these directories if you specified.
  include_dir = []
  
  # Watch these files.
  include_file = []
  
  # Exclude files.
  exclude_file = []
  
  # Exclude specific regular expressions.
  exclude_regex = ["_test\\.go", ".*\\.pb\\.go", ".*\\.gen\\.go", "mock_.*\\.go"]
  
  # Exclude unchanged files.
  exclude_unchanged = true
  
  # Follow symlink for directories
  follow_symlink = false
  
  # This log file places in your tmp_dir.
  log = "build-errors.log"
  
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000 # ms
  
  # Stop running old binary when build errors occur.
  stop_on_error = true
  
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = true
  
  # Delay after sending Interrupt signal
  kill_delay = 500 # ms
  
  # Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
  args_bin = []

  # Show log time
  time = true

[color]
  # Customize each part's color. If no color found, use the raw app log.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
  app = ""

[log]
  # Delete the log file on each run
  clean_on_exit = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true